chat_channels_integrations:
  chat_channels_integrations_enabled:
    default: false
    client: true
  chat_channels_integrations_matrix_homeserver:
    default: "https://matrix.org"
  chat_channels_integrations_matrix_access_token:
    default: ""
    secret: true
  chat_channels_integrations_matrix_use_notice:
    default: true
